### LT-RU-PL PLUS CHILD MODEL ###

# Vocabulary files
src_vocab: '/home/lbr/bpe_data/mass_data/mass.vocab.txt'
share_vocab: True
src_vocab_size: 100000
tgt_vocab_size: 100000

# Corpus opts
data:
    corpus_1:
        path_src: '/home/lbr/bpe_data/final_data/tune_data/lit_tune/lit_tune_helpers/final_lt-ru-pl_src_tune_bpe.txt'
        path_tgt: '/home/lbr/bpe_data/final_data/tune_data/lit_tune/lit_tune_helpers/final_lt-ru-pl_tgt_tune_bpe.txt'
    valid:
        path_src: '/home/lbr/bpe_data/final_data/tune_data/lit_tune/final_lt_val_bpe.txt'
        path_tgt: '/home/lbr/bpe_data/final_data/tune_data/lit_tune/final_lt_en_val_bpe.txt'

# Save checkpoints
save_model: '/home/lbr/saved_models/final_output/tune/lit/lt-ru-pl_arb_model'
save_checkpoint_steps: 1000
keep_checkpoint: 15

# Train and validation steps 
train_steps: 220000
valid_steps: 500
report_every: 100
seed: 3435

# GPU
world_size: 4
gpu_ranks: [0,1,2,3]

# Batching
batch_type: 'tokens' 
batch_size: 2000
valid_batch_size: 2000
accum_count: 2

max_generator_batches: 2

# Optimization
optim: "adam"
learning_rate: 3
warmup_steps: 30000
decay_method: "noam"
adam_beta1: 0.9
adam_beta2: 0.998
max_grad_norm: 0.0

share_decoder_embeddings: true
share_embeddings: true
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
position_encoding: true
normalization: "tokens"

# Model
encoder_type: transformer
decoder_type: transformer
enc_layers: 6
dec_layers: 6
heads: 8
rnn_size: 512
word_vec_size: 512
transformer_ff: 2048

dropout: [0.2]
attention_dropout: [0.2]